# Generated by Django 4.0.6 on 2022-07-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'MAN'), ('F', 'WOMAN')], max_length=255),
        ),
    ]
