# Generated by Django 4.0.6 on 2022-08-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailCocktail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('eng_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=100)),
                ('alcohol', models.CharField(max_length=20)),
                ('taste', models.CharField(max_length=20)),
                ('base', models.CharField(max_length=20)),
                ('match_food', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cocktail_cocktail',
                'managed': False,
            },
        ),
    ]
