# Generated by Django 4.0.6 on 2022-08-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='type',
            field=models.CharField(choices=[('C', 'Cocktail'), ('K', 'K-ocktail')], default='C', max_length=1),
            preserve_default=False,
        ),
    ]
