# Generated by Django 4.0.6 on 2022-08-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
