# Generated by Django 4.0.6 on 2022-08-16 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktail', '0002_cocktail_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='cocktail',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_cocktail', through='cocktail.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='star_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='stars',
            field=models.ManyToManyField(blank=True, related_name='star_cocktail', through='cocktail.Star', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='star',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktail.cocktail'),
        ),
        migrations.AddField(
            model_name='star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='like',
            name='cocktail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktail.cocktail'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
