# Generated by Django 4.0.6 on 2022-08-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0003_cocktail_like_cocktail_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='alcohol',
            field=models.IntegerField(),
        ),
    ]
