# Generated by Django 4.0.6 on 2022-08-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktail', '0003_cocktail_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
